# Generated by tasks_manager sync. Edit tasks.yaml, not this file.

add_task(NAME "itmo__alg_contests__01__a1_square_rects" DIRECTORY "itmo/alg_contests/01/a1_square_rects" INCLUDE_TESTS OFF SOURCES)

add_task(NAME "itmo__alg_contests__01__b1_redundant_whitespaces" DIRECTORY "itmo/alg_contests/01/b1_redundant_whitespaces" INCLUDE_TESTS OFF SOURCES)

add_task(NAME "itmo__alg_contests__01__c1_cacl_rpn" DIRECTORY "itmo/alg_contests/01/c1_cacl_rpn" INCLUDE_TESTS OFF SOURCES)

add_task(NAME "itmo__alg_contests__01__d2_simulate_queue" DIRECTORY "itmo/alg_contests/01/d2_simulate_queue" INCLUDE_TESTS OFF SOURCES)

add_task(NAME "itmo__alg_contests__01__e2_schizo_professor" DIRECTORY "itmo/alg_contests/01/e2_schizo_professor" INCLUDE_TESTS OFF SOURCES)

add_task(NAME "itmo__alg_homeworks__02__hw2_task4" DIRECTORY "itmo/alg_homeworks/02/hw2_task4" INCLUDE_TESTS ON SOURCES "solution.cpp")

add_task(NAME "itmo__alg_homeworks__02__hw2_task5" DIRECTORY "itmo/alg_homeworks/02/hw2_task5" INCLUDE_TESTS ON SOURCES "solution.cpp")

add_task(NAME "itmo__alg_homeworks__02__hw2_task6" DIRECTORY "itmo/alg_homeworks/02/hw2_task6" INCLUDE_TESTS ON SOURCES "solution.cpp")

add_task(NAME "leetcode__easy__concatenation_of_array" DIRECTORY "leetcode/easy/concatenation_of_array" INCLUDE_TESTS OFF SOURCES)

add_task(NAME "leetcode__easy__find-all-numbers-disappeared-in-an-array" DIRECTORY "leetcode/easy/find-all-numbers-disappeared-in-an-array" INCLUDE_TESTS ON SOURCES "solution.cpp")

add_task(NAME "leetcode__easy__how-many-numbers-are-smaller-than-the-current-number" DIRECTORY "leetcode/easy/how-many-numbers-are-smaller-than-the-current-number" INCLUDE_TESTS ON SOURCES "solution.cpp")

add_task(NAME "leetcode__easy__max_consecutive_ones" DIRECTORY "leetcode/easy/max_consecutive_ones" INCLUDE_TESTS ON SOURCES)

add_task(NAME "leetcode__easy__set_mismatch" DIRECTORY "leetcode/easy/set_mismatch" INCLUDE_TESTS ON SOURCES "solution.cpp")

add_task(NAME "leetcode__easy__shuffle_the_array" DIRECTORY "leetcode/easy/shuffle_the_array" INCLUDE_TESTS OFF SOURCES)

add_task(NAME "leetcode__medium__build-an-array-with-stack-operations" DIRECTORY "leetcode/medium/build-an-array-with-stack-operations" INCLUDE_TESTS ON SOURCES "Solution.cpp")

add_task(NAME "leetcode__medium__evaluate-reverse-polish-notation" DIRECTORY "leetcode/medium/evaluate-reverse-polish-notation" INCLUDE_TESTS ON SOURCES "Solution.cpp")

add_task(NAME "leetcode__medium__exclusive-time-of-functions" DIRECTORY "leetcode/medium/exclusive-time-of-functions" INCLUDE_TESTS ON SOURCES "Solution.cpp")

add_task(NAME "leetcode__medium__not_bouncy_numbers" DIRECTORY "leetcode/medium/not_bouncy_numbers" INCLUDE_TESTS OFF SOURCES)

