use std::collections::BTreeMap;

use crate::{Report, manifest::Task};

pub fn render(tasks: &[Task]) -> String {
    let mut text =
        String::from("# Generated by tasks_manager sync. Edit tasks.yaml, not this file.\n\n");
    for task in tasks {
        text.push_str(&declaration(task));
        text.push('\n');
    }
    text
}

fn declaration(task: &Task) -> String {
    let sources = task
        .source_files
        .iter()
        .map(|s| format!(" \"{s}\""))
        .collect::<String>();
    format!(
        "add_task(NAME \"{}\" DIRECTORY \"{}\" INCLUDE_TESTS {} SOURCES{})\n",
        task.name,
        task.directory,
        if task.include_tests { "ON" } else { "OFF" },
        sources
    )
}

// Read only our generated declarations; never execute or parse arbitrary CMake.
fn declarations(text: &str) -> BTreeMap<String, String> {
    text.lines()
        .filter_map(|line| {
            let rest = line.strip_prefix("add_task(NAME \"")?;
            let (name, _) = rest.split_once('"')?;
            Some((name.to_owned(), line.to_owned()))
        })
        .collect()
}

pub fn diff(old: &str, new: &str, report: &mut Report) {
    let old = declarations(old);
    let new = declarations(new);
    for (name, declaration) in &new {
        match old.get(name) {
            None => report.added.push(name.clone()),
            Some(previous) if previous != declaration => report
                .updated
                .push(format!("{name}\n    - {previous}\n    + {declaration}")),
            _ => {}
        }
    }
    report
        .removed
        .extend(old.keys().filter(|name| !new.contains_key(*name)).cloned());
}
